{{- include "nvidia-warehouse.assertSafety" . -}}
{{- if .Values.global.enabled }}
{{- range $key, $account := .Values.serviceAccounts }}
{{- if $account.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $account.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "nvidia-warehouse.labels" (dict "root" $ "component" (printf "serviceaccount-%s" $key)) | nindent 4 }}
{{- with $.Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
