{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vast-vss-app.serviceAccountName" . }}
  labels:
    {{- include "vast-vss-app.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
